### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [dweiss/java-sizeof#1]
Hi
The following source files are without license headers:

./src/main/java/com/carrotsearch/sizeof/IdentityHashSet.java
./src/main/java/com/carrotsearch/sizeof/BlackMagic.java
./src/main/java/com/carrotsearch/sizeof/ObjectTree.java
./src/main/java/com/carrotsearch/sizeof/MurmurHash3.java
./src/test/java/com/carrotsearch/sizeof/experiments/ExpSubclassAlignment.java
./src/test/java/com/carrotsearch/sizeof/experiments/ExpMemoryDumper.java
./src/test/java/com/carrotsearch/sizeof/experiments/WildClasses.java
./src/test/java/com/carrotsearch/sizeof/experiments/GenerateWildClasses.java
./src/test/java/com/carrotsearch/sizeof/TestLongChains.java
./src/test/java/com/carrotsearch/sizeof/TestSanity.java
./src/test/java/com/carrotsearch/sizeof/TestIdentityHashSet.java
./src/test/java/com/carrotsearch/sizeof/TestEstimationQuality.java
./src/test/java/com/carrotsearch/sizeof/TestFieldReorderingInClassHierarchy.java
./src/test/java/com/carrotsearch/sizeof/TestProcessingLargeGraph.java

Please, confirm the licensing of code and/or content/s, and add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance
Regards

**Comment by dweiss** [comment]
Please provide a pull request if you care. All the sources in the project are governed by the top level license, this is legally binding and there is no need to copy it all over the place.

**Comment by puntogil** [comment]
Done
